name: Main workflow
on: push
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ github.token }}
  GIT_COMMIT: docker-commit-message
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
      - name: run linting
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - run: bash ci/build-docker.sh
      - run: bash ci/push-docker.sh
